title: Rahul Karmakar # your name (or website title) here
logo: "/images/00100sPORTRAIT_00100_BURST20190606222537726_COVER__01.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  5 years of Data analyst and key accoount management experience.Possess MBA in Marketing from Indian Institute of Social Welfare and Business Management, Kolkata.
  <br><br>
  Currently associated with Zeta Global as Data Analyst. I am on the North American team, working with stakeholders and account managers to assist them with their reporting and analytical needs.
  <br><br>
  <a href="https://www.linkedin.com/in/rahulkarmakar1990/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
